### ISSUE TITLE
darch and runc are in conflict on arch linux

### ISSUE THREAD

**Issue by burkostya** [godarch/darch#17]
Installing darch on my archlinux returns
```sh
looking for conflicting packages...
:: darch and runc are in conflict. Remove runc? [y/N] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: darch and runc are in conflict
```
Is it possible to provide aur package without dependency on runc?

**Comment by pauldotknopf** [comment]
The runc in AUR is old.

As soon as containerd 1.0.2 and runc 1.0 (or even rc4) is in there, I will remove it.

By the way, the runc in darch is fully usable.

**Comment by burkostya** [comment]
Ok, thanks

**Comment by pauldotknopf** [comment]
Np.

By the way, the containerd/runc in darch are completely usable.
