### ISSUE TITLE
error on running darch's initcpio hook

### ISSUE THREAD

**Issue by burkostya** [godarch/darch#19]
Trying to boot staged image results with
```
:: running early hook [udev]
starting version 238
:: running early hook [lvm2]
:: running hook [udev]
:: Triggering uevents...
:: running hook [darch]
ERROR: device '' not found. Skipping fsck.
Darch mount handler
Trying to mount Darch source (UUID=6c9f...16c5)
mount: /image_source: can't find UUID=6c9f...16c5.
ERROR: Unable to mount Darch source: UUID=6c9f...16c5
You are being dropped to a shell
Try to mount your darch device in /image_source
sh: can't access tty; job control turned off
[rootfs ]#
```

Can you help me with finding out how to solve this issue?

**Comment by pauldotknopf** [comment]
The initramfs cannot mount the file system with the UUID ```UUID=6c9f...16c5```.

When this error happens, you are dropped to a shell. Try to mount this partition to ```/image_source```. Look in ```/dev/disk*``` for your disk. I suspect you will get mount errors, probably because of an unsupported file system type. You might have to add some additional arch hooks in your recipe to support whatever file system you are trying to mount.

**Comment by burkostya** [comment]
```
...
[rootfs ]# ls /image_source/
[rootfs ]# mount /dev/disk/by-uuid/6c9f...16c5 /image_source
[rootfs ]# ls /image_source/
containerd  lost+found  stage
[rootfs ]#
```

There is no mount error

**Comment by pauldotknopf** [comment]
The interactive shell allows you to attempt to fix the problem. Typing "exit" will continue the normal execution flow.

After you get the failure to mount, fix the problem, then type "exit". After doing this, does the system boot properly?

It may be that your disk isn't showing up quick enough. I may have to add a while loop for a certain amount of time to attempt to wait for the disk to become available.

**Comment by burkostya** [comment]
ok, thanks!

**Comment by burkostya** [comment]
Same error is here again. But now there is no image to mount.
Output of `ls /dev/disk/by-uuid` does not contain `6c9f...16c5`
There are no errors while `darch stage upload`
Any advice in resolving that issue? Or direction to dig?

There is a news about excluding kernel from `base` package - https://www.archlinux.org/news/base-group-replaced-by-mandatory-base-package-manual-intervention-required/ But i am not sure if it relates somehow.

Another differences are:
- Version of systemd. Last working image have 243-0-1-arch. On bad one it is 243-53-1-arch.
- `:: running early hook [lvm2]` does not present between `starting version 243-53-1-arch` and `:: running hook [udev]`. And after too.

**Comment by burkostya** [comment]
Problem solved after installing lvm2
