### ISSUE TITLE
error on installing darch's ssh hook

### ISSUE THREAD

**Issue by burkostya** [godarch/darch#20]
`darch stage upload i3' results with next error
```
cp: cannot stat /etc/ssh/ssh_host_* file or directory does not exists
```
on first run and with
```
cp: cannot stat /etc/darch/ssh/default/ssh_host_* file or directory does not exists
```
on second and any future runs

I think it raises from here https://github.com/godarch/darch/blob/develop/scripts/hooks/ssh
Disabling `ssh` hook fixes error

**Comment by pauldotknopf** [comment]
The script currently expects files to exists at ```/etc/ssh/ssh_host_*```. This would be patched to fail nicely if they don't exist.

In the mean time, instead openssh-server on your host machine to auto-generate those files.
