### ISSUE TITLE
error on pulling image

### ISSUE THREAD

**Issue by burkostya** [godarch/darch#22]
```
> sudo darch images pull docker.io/burkostya/darch-thinkpad-social
```
got
```
pulling docker.io/burkostya/darch-thinkpad-social:latest
darch: failed commit on ref "layer-sha256:3183c7921165b9faa69b30ac7e12fd2331269d3eb293e7eacd1e162cf4750a8c": unexpected commit digest sha256:c369a9d3be94e34864a4e0d4a7ad0fd7b7d86801f6f49cd900a4e8caaecc8a1a, expected sha256:3183c7921165b9faa69b30ac7e12fd2331269d3eb293e7eacd1e162cf4750a8c: unknown
```

How to fix it?

**Comment by pauldotknopf** [comment]
Hmm...

Do me a favor:

1. Setup a local Docker registry: https://docs.docker.com/registry/#alternatives
2. Build and push your Darch image to it.
3. Delete any existing images in Darch.
4. Pull your image from local registry into Darch.

Does this work?

**Comment by burkostya** [comment]
I deleted stuff related to the containerd and restarted it. After that everything works.
On the next time it will happen i will follow steps you provided. Thanks
Close for now
