### ISSUE TITLE
images pull fails - 503

### ISSUE THREAD

**Issue by cawilliamson** [godarch/darch#24]
When I try and pull the godarch/arch image I am getting:

```
# darch images pull godarch/arch
darch: failed to resolve reference "docker.io/godarch/arch:latest": failed to fetch anonymous token: unexpected status: 503 Service Unavailable
```

Any ideas? Sounds like it may be an issue at the docler.io side but just making sure I'm not missing something daft here.

**Comment by cawilliamson** [comment]
Nope, I wasn't missing anything. This was an issue at the docker.io side.

Working great again now! :)

**Comment by pauldotknopf** [comment]
Great!

Stop by the gitter lobby if you need help with anything!
