### ISSUE TITLE
grub.cfg doesn't get sourced & vmlinuz can't be found

### ISSUE THREAD

**Issue by shizonic** [godarch/darch#26]
After uploading a stage and recreating the grub config by running `grub-mkconfig -o /boot/grub/grub.cfg` the file `/etc/darch/grub.cfg` doesn't get sourced and therefore is no boot entry for darch available.

For test cases I just put the entry from `/etc/darch/grub.cfg` directly into `/boot/grub/grub.cfg` and the darch boot menu entry appears BUT if I try to boot I got an error message `/stage/live/s5dj4m06ct5ma4fq6u052oeqx/vmlinuz can not be found.`. What do I am make wrong?

**Comment by shizonic** [comment]
I managed to get both things working by myself.

The first one by adding my own custom grub.d entry. The second by mounting the root subvolume of my btrfs partition to /var/lib/darch.

Now I can really start to build my custom images. Amazing. Thanks!

**Comment by pauldotknopf** [comment]
Sorry I couldn't dig in more. I've been away from my comp.

Glad to know you got it solved!

**Comment by shizonic** [comment]
@pauldotknopf No problem. Thanks for any support and all your great work !
