### ISSUE TITLE
Question: VSCode debugging as root

### ISSUE THREAD

**Issue by shizonic** [godarch/darch#27]
Hi again

I am currently working on some personal improvements for darch and forked the repo.

After setting up my vscode for development (btw. vscode is awesome!) I tried to debug the gode using delve.

The problem is that I can't run darch as root with the vscode debugger. So I would like to ask you how you handle this?

Thanks for all your help.

**Comment by pauldotknopf** [comment]
I run VSCode as root. There is a switch you have to pass to ```code``` that sets a different config directory.

**Comment by shizonic** [comment]
Thanks for your reply. Yes I know that - it's `--user-data-dir`. But I was looking for a better approach. Isn't there one?

**Comment by pauldotknopf** [comment]
I'm afraid not, AFAIK.

**Comment by shizonic** [comment]
Okay, thanks anyway. 👍
