### ISSUE TITLE
Error on stage upload after updating to 0.26.4

### ISSUE THREAD

**Issue by burkostya** [godarch/darch#31]
Got error on uploading to stage after updating darch up to 0.26.4 from 0.21
```
> sudo darch stage upload docker.io/burkostya/darch-thinkpad-design:2018-11-08-010010
darch: ttrpc: client shutting down: read unix @->@/containerd-shim/darch/jw5glraou38iq9yaam1w66gru/shim.sock: read: connection reset by peer: unknown
```

image pull is working

**Comment by pauldotknopf** [comment]
Bummer.

I removed the bundling of containers and runc because the ones in the official repos were finally up to date.

But, there seems to a bug in containerd.

I suspect it is segfaulting. Can you give me the journalctl for containerd?

**Comment by pauldotknopf** [comment]
Also, if you wouldn't mind, could you update the runc and containerd binaries to these commits?

https://github.com/opencontainers/runc/tree/4fc53a81fb7c994640722ac585fa9ca548971871

https://github.com/containerd/containerd/tree/c4446665cb9c30056f4998ed953e6d4ff22c7c39

**Comment by pauldotknopf** [comment]
Im in the middle of preparing a Darch VM for users wanting to evaluate Darch. I should have it wrapped up in a few days.

I will get to this issue right after.

In the meantime, I recommend manual building Darch using makepkg at the version (in the aur repo) that worked for you.

There wasn't anything worth updating in your case. Most of the changes were to get the new Debian and Ubuntu distributions working.

**Comment by burkostya** [comment]
Problem was with containerd package. After updating from containerd-1.2.0-1 to containerd-1.2.0-2 stage uploading works as should

**Comment by pauldotknopf** [comment]
Great to hear! Thanks for the update!

I was literally JUST getting my Arch image booted to test it.
