### ISSUE TITLE
Darch fails with "failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded"

### ISSUE THREAD

**Issue by phunni** [godarch/darch#39]
When I run 

> darch images pull godarch/arch  

as root it fails with 

> darch: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded

**Comment by pauldotknopf** [comment]
Is this on Arch? Can you verify that file exists? It is created by the containerd daemon.

**Comment by phunni** [comment]
Ah - sorry my mistake. I hadn't appreciated that containerd needs to be running. It now works if I have the daemon running. Am I better off using an installation of darch with containerd built in?

Edit: yes, this in on Arch and I installed darch via aur.
