### ISSUE TITLE
Arch Linux kernel installation Confusion

### ISSUE THREAD

**Issue by elovin** [godarch/darch#52]
I installed darch through the aur and pulled the arch linux base image,
the documentation states that I have to install the kernel and rebuild the initramfs, but I dont get in what context. I suppose I have to install the kernel within the containerd image which is confusing to me since I only know docker images.

So am I supposed to install the kernel inside the arch linux image or somehow hook my host system kernel into the image ?

**Comment by pauldotknopf** [comment]
If your base image inherits ```godarch/arch``` ([here](https://hub.docker.com/r/godarch/arch)), then the initramfs scripts are already setup (see [here](https://github.com/godarch/distributions/blob/master/arch/Dockerfile#L7)).

What documentation are you referring to?

**Comment by elovin** [comment]
> If your base image inherits `godarch/arch` ([here](https://hub.docker.com/r/godarch/arch)), then the initramfs scripts are already setup (see [here](https://github.com/godarch/distributions/blob/master/arch/Dockerfile#L7)).
> 
> What documentation are you referring to?

Thanks for the quick reply.

I'm referring to [this](https://godarch.com/concepts/recipes/distributions/) part of the documentation. 

I'm trying to run the base image directly (I want to try it out before I extend it) so I pulled godarch/arch and then tried to upload it `sudo darch stage upload godarch/arch`
which results in `cp: cannot stat '/boot/vmlinuz-linux': No such file or directory`.

**Comment by pauldotknopf** [comment]
> I'm referring to this part of the documentation.

Ah. You initramfs *hooks* are in the image. Just install the kernel and run ```mkinitcpio -p linux``` in the image and you should be good.

> I'm trying to run the base image directly

Yeah, you need to create a derived image that has the kernel installed. Besides, you'd want to do some other stuff as well. Checkout my old Arch recipes [here](https://github.com/pauldotknopf/darch-recipes/tree/2945b2d61c797fd86b9b14c786c0067943fa369c).

**Comment by elovin** [comment]
@pauldotknopf Thanks I will try that
