### ISSUE TITLE
godarch.com gone?

### ISSUE THREAD

**Issue by rayvermey** [godarch/darch#62]
Hi , this project looks interesting but the site can't be reached??

**Comment by leeferwagen** [comment]
Hi @rayvermey,

according to [DropCatch](https://www.dropcatch.com/domain/godarch.com) the domain is gone:
> This domain auction ended on Tuesday, April 11, 2023 at 9:00 PM

**Comment by Cfrolich13** [comment]
I’ll put the last Wayback Machine snapshot here for everyone’s convenience:
[https://web.archive.org/web/20230128034151/https://godarch.com/](https://web.archive.org/web/20230128034151/https://godarch.com/) 

@godarch, are you aware of this issue?

**Comment by czardien** [comment]
Yep it's down.

**Comment by pauldotknopf** [comment]
Sorry guys. Yeah, I've moved on.

**Comment by GrabbenD** [comment]
@pauldotknopf I absolutely love the idea of Darch. Do you use something else now?

_PS Github Pages could potentially be used to host the documentation for free_

---

**Edit**: went with OSTree
https://github.com/GrabbenD/ostree-utility

**Comment by pauldotknopf** [comment]
I got a new job and I develop on a Mac now.

Also, I put Windows on my old laptop (which had Darch) because I use it for audio editing now (Ableton, etc).

**Comment by SuNNjek** [comment]
When I click the link now it redirects me a very sketchy looking domain. Luckily uBlock blocks that site but you might consider removing the link from the readme.
